apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-django
  name: deployment-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-django
    spec:
      containers:
      - image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labpr>
        name: kontener-django
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-django
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret-django
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-django
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: cmap-django
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: cmap-django
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: cmap-django
              key: DB_PORT
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: cmap-django
              key: PORT
        volumeMounts:
        - name: backend-persistent-storage
          mountPath: /files/phone
      volumes:
      - name: backend-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-django